swagger: "2.0"
info:
    title: Chat API
    description: Chat API
    version: "0.1"
host: localhost:8000
basePath: /
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /api/channels:
        get:
            tags:
                - channels
            summary: list channels
            operationId: channels#list
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ChannelsListResponseBody'
            schemes:
                - http
        post:
            tags:
                - channels
            summary: create channels
            operationId: channels#create
            parameters:
                - name: CreateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/ChannelsCreateRequestBody'
                    required:
                        - name
            responses:
                "201":
                    description: Created response.
                    schema:
                        $ref: '#/definitions/ChannelsCreateResponseBody'
            schemes:
                - http
    /api/channels/{id}:
        get:
            tags:
                - channels
            summary: show channels
            operationId: channels#show
            parameters:
                - name: id
                  in: path
                  description: ID
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ChannelsShowResponseBody'
            schemes:
                - http
        put:
            tags:
                - channels
            summary: update channels
            operationId: channels#update
            parameters:
                - name: id
                  in: path
                  description: ID
                  required: true
                  type: integer
                - name: UpdateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/ChannelsUpdateRequestBody'
                    required:
                        - name
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ChannelsUpdateResponseBody'
            schemes:
                - http
        delete:
            tags:
                - channels
            summary: delete channels
            operationId: channels#delete
            parameters:
                - name: id
                  in: path
                  description: ID
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ChannelsDeleteResponseBody'
            schemes:
                - http
definitions:
    ChannelListItemResponseBody:
        title: 'Mediatype identifier: application/vnd.channel-list-item; view=default'
        type: object
        properties:
            created_at:
                type: string
                description: CreatedAt
                example: 2006-01-02T15:04:05Z07:00
                format: date-time
            id:
                type: integer
                description: ID
                example: 10920462265724847802
                format: int64
            name:
                type: string
                description: Name
                example: Quia consectetur qui.
            updated_at:
                type: string
                description: UpdatedAt
                example: 2006-01-02T15:04:05Z07:00
                format: date-time
        description: Channel-List-ItemResponseBody result type (default view)
        example:
            created_at: 2006-01-02T15:04:05Z07:00
            id: 6695709217680786680
            name: Labore odit et reiciendis qui.
            updated_at: 2006-01-02T15:04:05Z07:00
        required:
            - id
            - created_at
            - updated_at
            - name
    ChannelListItemResponseBodyCollection:
        title: 'Mediatype identifier: application/vnd.channel-list-item; type=collection; view=default'
        type: array
        items:
            $ref: '#/definitions/ChannelListItemResponseBody'
        description: Channel-List-ItemCollectionResponseBody is the result type for an array of Channel-List-ItemResponseBody (default view)
        example:
            - created_at: 2006-01-02T15:04:05Z07:00
              id: 6978203180985993855
              name: Culpa aliquid.
              updated_at: 2006-01-02T15:04:05Z07:00
            - created_at: 2006-01-02T15:04:05Z07:00
              id: 6978203180985993855
              name: Culpa aliquid.
              updated_at: 2006-01-02T15:04:05Z07:00
            - created_at: 2006-01-02T15:04:05Z07:00
              id: 6978203180985993855
              name: Culpa aliquid.
              updated_at: 2006-01-02T15:04:05Z07:00
            - created_at: 2006-01-02T15:04:05Z07:00
              id: 6978203180985993855
              name: Culpa aliquid.
              updated_at: 2006-01-02T15:04:05Z07:00
    ChannelsCreateRequestBody:
        title: ChannelsCreateRequestBody
        type: object
        properties:
            name:
                type: string
                description: Name
                example: Animi ut aut totam.
        example:
            name: Inventore expedita dolores quia est.
        required:
            - name
    ChannelsCreateResponseBody:
        title: 'Mediatype identifier: application/vnd.channel; view=default'
        type: object
        properties:
            created_at:
                type: string
                description: CreatedAt
                example: 2006-01-02T15:04:05Z07:00
                format: date-time
            id:
                type: integer
                description: ID
                example: 1436963588651385446
                format: int64
            name:
                type: string
                description: Name
                example: Similique ut.
            updated_at:
                type: string
                description: UpdatedAt
                example: 2006-01-02T15:04:05Z07:00
                format: date-time
        description: CreateResponseBody result type (default view)
        example:
            created_at: 2006-01-02T15:04:05Z07:00
            id: 18434525792707224430
            name: Qui natus molestias incidunt rerum.
            updated_at: 2006-01-02T15:04:05Z07:00
        required:
            - id
            - created_at
            - updated_at
            - name
    ChannelsDeleteResponseBody:
        title: 'Mediatype identifier: application/vnd.channel; view=default'
        type: object
        properties:
            created_at:
                type: string
                description: CreatedAt
                example: 2006-01-02T15:04:05Z07:00
                format: date-time
            id:
                type: integer
                description: ID
                example: 14931247875723354875
                format: int64
            name:
                type: string
                description: Name
                example: Aperiam culpa repellendus voluptatem sit aut.
            updated_at:
                type: string
                description: UpdatedAt
                example: 2006-01-02T15:04:05Z07:00
                format: date-time
        description: DeleteResponseBody result type (default view)
        example:
            created_at: 2006-01-02T15:04:05Z07:00
            id: 12524187808354141556
            name: Et dolorum est qui.
            updated_at: 2006-01-02T15:04:05Z07:00
        required:
            - id
            - created_at
            - updated_at
            - name
    ChannelsListResponseBody:
        title: 'Mediatype identifier: application/vnd.channel-list; view=default'
        type: object
        properties:
            items:
                $ref: '#/definitions/ChannelListItemResponseBodyCollection'
            offset:
                type: integer
                description: Offset
                example: 0
                format: int64
            total:
                type: integer
                description: Total number of items
                example: 160
                format: int64
        description: ListResponseBody result type (default view)
        example:
            items:
                - created_at: 2006-01-02T15:04:05Z07:00
                  id: 6978203180985993855
                  name: Culpa aliquid.
                  updated_at: 2006-01-02T15:04:05Z07:00
                - created_at: 2006-01-02T15:04:05Z07:00
                  id: 6978203180985993855
                  name: Culpa aliquid.
                  updated_at: 2006-01-02T15:04:05Z07:00
                - created_at: 2006-01-02T15:04:05Z07:00
                  id: 6978203180985993855
                  name: Culpa aliquid.
                  updated_at: 2006-01-02T15:04:05Z07:00
                - created_at: 2006-01-02T15:04:05Z07:00
                  id: 6978203180985993855
                  name: Culpa aliquid.
                  updated_at: 2006-01-02T15:04:05Z07:00
            offset: 0
            total: 160
        required:
            - items
            - total
            - offset
    ChannelsShowResponseBody:
        title: 'Mediatype identifier: application/vnd.channel; view=default'
        type: object
        properties:
            created_at:
                type: string
                description: CreatedAt
                example: 2006-01-02T15:04:05Z07:00
                format: date-time
            id:
                type: integer
                description: ID
                example: 15023269934203985894
                format: int64
            name:
                type: string
                description: Name
                example: Numquam nihil.
            updated_at:
                type: string
                description: UpdatedAt
                example: 2006-01-02T15:04:05Z07:00
                format: date-time
        description: ShowResponseBody result type (default view)
        example:
            created_at: 2006-01-02T15:04:05Z07:00
            id: 15203894610385654585
            name: Dolorem optio consequatur est eligendi.
            updated_at: 2006-01-02T15:04:05Z07:00
        required:
            - id
            - created_at
            - updated_at
            - name
    ChannelsUpdateRequestBody:
        title: ChannelsUpdateRequestBody
        type: object
        properties:
            name:
                type: string
                description: Name
                example: Aut consequuntur sit dignissimos aspernatur qui aut.
        example:
            name: Molestiae corrupti nihil.
        required:
            - name
    ChannelsUpdateResponseBody:
        title: 'Mediatype identifier: application/vnd.channel; view=default'
        type: object
        properties:
            created_at:
                type: string
                description: CreatedAt
                example: 2006-01-02T15:04:05Z07:00
                format: date-time
            id:
                type: integer
                description: ID
                example: 12295936051785577711
                format: int64
            name:
                type: string
                description: Name
                example: In similique.
            updated_at:
                type: string
                description: UpdatedAt
                example: 2006-01-02T15:04:05Z07:00
                format: date-time
        description: UpdateResponseBody result type (default view)
        example:
            created_at: 2006-01-02T15:04:05Z07:00
            id: 4342935428259852073
            name: Provident tempora dolor ratione officiis consequatur.
            updated_at: 2006-01-02T15:04:05Z07:00
        required:
            - id
            - created_at
            - updated_at
            - name
