openapi: 3.0.3
info:
    title: Chat API
    description: Chat API
    version: "0.1"
servers:
    - url: http://localhost:8000
paths:
    /api/channels:
        get:
            tags:
                - channels
            summary: list channels
            operationId: channels#list
            parameters:
                - name: session_id
                  in: cookie
                  description: Session ID
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Session ID
                    example: Dolores modi perspiciatis.
                  example: Asperiores assumenda nisi dignissimos minima ducimus.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ChannelList'
                            example:
                                items:
                                    - created_at: 2006-01-02T15:04:05Z07:00
                                      id: 7271062959787804439
                                      name: Eos et excepturi aut asperiores.
                                      updated_at: 2006-01-02T15:04:05Z07:00
                                    - created_at: 2006-01-02T15:04:05Z07:00
                                      id: 7271062959787804439
                                      name: Eos et excepturi aut asperiores.
                                      updated_at: 2006-01-02T15:04:05Z07:00
                                    - created_at: 2006-01-02T15:04:05Z07:00
                                      id: 7271062959787804439
                                      name: Eos et excepturi aut asperiores.
                                      updated_at: 2006-01-02T15:04:05Z07:00
                                    - created_at: 2006-01-02T15:04:05Z07:00
                                      id: 7271062959787804439
                                      name: Eos et excepturi aut asperiores.
                                      updated_at: 2006-01-02T15:04:05Z07:00
                                offset: 0
                                total: 160
                "401":
                    description: 'unauthenticated: Unauthorized response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - channels
            summary: create channels
            operationId: channels#create
            parameters:
                - name: session_id
                  in: cookie
                  description: Session ID
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Session ID
                    example: Sapiente incidunt.
                  example: Eum nostrum omnis.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody'
                        example:
                            name: Ex cumque et ipsa voluptate ullam.
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Channel'
                            example:
                                created_at: 2006-01-02T15:04:05Z07:00
                                id: 3174728128026383618
                                name: Modi ullam excepturi earum.
                                updated_at: 2006-01-02T15:04:05Z07:00
                "400":
                    description: 'invalid_payload: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "401":
                    description: 'unauthenticated: Unauthorized response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/channels/{id}:
        delete:
            tags:
                - channels
            summary: delete channels
            operationId: channels#delete
            parameters:
                - name: id
                  in: path
                  description: ID
                  required: true
                  schema:
                    type: integer
                    description: ID
                    example: 4136619047964399000
                  example: 13148434870933640335
                - name: session_id
                  in: cookie
                  description: Session ID
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Session ID
                    example: Cumque facere molestias sit quos sint autem.
                  example: Amet soluta et.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Channel'
                            example:
                                created_at: 2006-01-02T15:04:05Z07:00
                                id: 4844715748500730359
                                name: Quo alias saepe recusandae qui similique.
                                updated_at: 2006-01-02T15:04:05Z07:00
                "401":
                    description: 'unauthenticated: Unauthorized response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'not_found: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        get:
            tags:
                - channels
            summary: show channels
            operationId: channels#show
            parameters:
                - name: id
                  in: path
                  description: ID
                  required: true
                  schema:
                    type: integer
                    description: ID
                    example: 7987123220964923734
                  example: 4596225480331733083
                - name: session_id
                  in: cookie
                  description: Session ID
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Session ID
                    example: Nisi earum quo odio et minima ex.
                  example: Dolor maxime aliquid qui qui.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Channel'
                            example:
                                created_at: 2006-01-02T15:04:05Z07:00
                                id: 821952026860172930
                                name: Sit aut quia quas et dolorum.
                                updated_at: 2006-01-02T15:04:05Z07:00
                "401":
                    description: 'unauthenticated: Unauthorized response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'not_found: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        put:
            tags:
                - channels
            summary: update channels
            operationId: channels#update
            parameters:
                - name: id
                  in: path
                  description: ID
                  required: true
                  schema:
                    type: integer
                    description: ID
                    example: 4114453224574389686
                  example: 15299665101878974479
                - name: session_id
                  in: cookie
                  description: Session ID
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Session ID
                    example: Quia nisi eos atque.
                  example: Quibusdam vel cum ea.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody'
                        example:
                            name: Quo ratione et.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Channel'
                            example:
                                created_at: 2006-01-02T15:04:05Z07:00
                                id: 6530557858022878942
                                name: Quas earum in omnis quasi.
                                updated_at: 2006-01-02T15:04:05Z07:00
                "400":
                    description: 'invalid_payload: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "401":
                    description: 'unauthenticated: Unauthorized response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'not_found: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/chat_messages:
        get:
            tags:
                - chat_messages
            summary: list chat_messages
            operationId: chat_messages#list
            parameters:
                - name: limit
                  in: query
                  description: Limit
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: integer
                    description: Limit
                    default: 50
                    example: 1728859348663760869
                    format: int64
                  example: 3662983257080283864
                - name: channel_id
                  in: query
                  description: Channel ID
                  allowEmptyValue: true
                  schema:
                    type: integer
                    description: Channel ID
                    example: 9677936816436211330
                  example: 819908799023234533
                - name: after
                  in: query
                  description: ChatMessage ID for query to get messages after this
                  allowEmptyValue: true
                  schema:
                    type: integer
                    description: ChatMessage ID for query to get messages after this
                    example: 4165104743597425938
                  example: 1614485646083767173
                - name: before
                  in: query
                  description: ChatMessage ID for query to get messages before this
                  allowEmptyValue: true
                  schema:
                    type: integer
                    description: ChatMessage ID for query to get messages before this
                    example: 15196083335568763879
                  example: 412306065014351940
                - name: session_id
                  in: cookie
                  description: Session ID
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Session ID
                    example: Provident rerum blanditiis.
                  example: Aliquid aperiam doloribus hic voluptatem at.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ChatMessageList'
                            example:
                                items:
                                    - channel_id: 17409760595284137384
                                      content: Et est nesciunt perspiciatis optio rerum.
                                      created_at: 2006-01-02T15:04:05Z07:00
                                      id: 6470953216617523288
                                      updated_at: 2006-01-02T15:04:05Z07:00
                                      user_id: 3571536357390730231
                                      user_name: Repudiandae consequatur officia dolores corporis asperiores.
                                    - channel_id: 17409760595284137384
                                      content: Et est nesciunt perspiciatis optio rerum.
                                      created_at: 2006-01-02T15:04:05Z07:00
                                      id: 6470953216617523288
                                      updated_at: 2006-01-02T15:04:05Z07:00
                                      user_id: 3571536357390730231
                                      user_name: Repudiandae consequatur officia dolores corporis asperiores.
                                    - channel_id: 17409760595284137384
                                      content: Et est nesciunt perspiciatis optio rerum.
                                      created_at: 2006-01-02T15:04:05Z07:00
                                      id: 6470953216617523288
                                      updated_at: 2006-01-02T15:04:05Z07:00
                                      user_id: 3571536357390730231
                                      user_name: Repudiandae consequatur officia dolores corporis asperiores.
                "401":
                    description: 'unauthenticated: Unauthorized response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - chat_messages
            summary: create chat_messages
            operationId: chat_messages#create
            parameters:
                - name: session_id
                  in: cookie
                  description: Session ID
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Session ID
                    example: Molestiae qui nam perspiciatis recusandae.
                  example: Dignissimos nam laborum impedit consequatur.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody2'
                        example:
                            channel_id: 3874821448833755012
                            content: Consequatur unde est exercitationem occaecati est fugit.
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ChatMessage'
                            example:
                                channel_id: 14768943193252204717
                                content: Suscipit voluptas sit quos enim praesentium provident.
                                created_at: 2006-01-02T15:04:05Z07:00
                                id: 3651070506478260572
                                updated_at: 2006-01-02T15:04:05Z07:00
                                user_id: 2078621645422433149
                                user_name: In et modi nam.
                "400":
                    description: 'invalid_payload: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "401":
                    description: 'unauthenticated: Unauthorized response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/chat_messages/{id}:
        delete:
            tags:
                - chat_messages
            summary: delete chat_messages
            operationId: chat_messages#delete
            parameters:
                - name: id
                  in: path
                  description: ID
                  required: true
                  schema:
                    type: integer
                    description: ID
                    example: 9167115254448531536
                  example: 625015297926360778
                - name: session_id
                  in: cookie
                  description: Session ID
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Session ID
                    example: Quae cum voluptatem.
                  example: Modi commodi.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ChatMessage'
                            example:
                                channel_id: 17146100472362209096
                                content: Dicta laborum veritatis.
                                created_at: 2006-01-02T15:04:05Z07:00
                                id: 4266831331324030037
                                updated_at: 2006-01-02T15:04:05Z07:00
                                user_id: 2266956969172765303
                                user_name: Quia est necessitatibus eum.
                "401":
                    description: 'unauthenticated: Unauthorized response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'not_found: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        get:
            tags:
                - chat_messages
            summary: show chat_messages
            operationId: chat_messages#show
            parameters:
                - name: id
                  in: path
                  description: ID
                  required: true
                  schema:
                    type: integer
                    description: ID
                    example: 5373567929324953157
                  example: 15639366818451377674
                - name: session_id
                  in: cookie
                  description: Session ID
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Session ID
                    example: Non voluptas excepturi a ut deleniti.
                  example: Odio temporibus.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ChatMessage'
                            example:
                                channel_id: 13169732932582615688
                                content: Quo minus quas voluptatibus consequatur nemo.
                                created_at: 2006-01-02T15:04:05Z07:00
                                id: 11010856570215230736
                                updated_at: 2006-01-02T15:04:05Z07:00
                                user_id: 10730748131142922952
                                user_name: Nulla fugit porro recusandae velit consequatur dolores.
                "401":
                    description: 'unauthenticated: Unauthorized response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'not_found: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        put:
            tags:
                - chat_messages
            summary: update chat_messages
            operationId: chat_messages#update
            parameters:
                - name: id
                  in: path
                  description: ID
                  required: true
                  schema:
                    type: integer
                    description: ID
                    example: 8266720457803263495
                  example: 2721118599147601557
                - name: session_id
                  in: cookie
                  description: Session ID
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Session ID
                    example: Dolore voluptatem ex tenetur consequatur optio.
                  example: Ullam officiis qui ducimus laborum.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateRequestBody'
                        example:
                            content: Nihil aliquam dicta.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ChatMessage'
                            example:
                                channel_id: 4377340767052073861
                                content: Inventore unde voluptas voluptatem quam velit et.
                                created_at: 2006-01-02T15:04:05Z07:00
                                id: 13886048143001497827
                                updated_at: 2006-01-02T15:04:05Z07:00
                                user_id: 8678752748511384800
                                user_name: Animi ab.
                "400":
                    description: 'invalid_payload: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "401":
                    description: 'unauthenticated: Unauthorized response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'not_found: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/session:
        delete:
            tags:
                - sessions
            summary: delete sessions
            operationId: sessions#delete
            parameters:
                - name: session_id
                  in: cookie
                  description: Session ID
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Session ID
                    example: Quo dolorem libero voluptas quia dolore.
                  example: Perspiciatis delectus.
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'invalid_payload: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - sessions
            summary: create sessions
            operationId: sessions#create
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody3'
                        example:
                            id_token: Ipsa et minima quaerat omnis adipisci.
            responses:
                "201":
                    description: Created response.
                    headers:
                        Set-Cookie:
                            description: Session ID
                            schema:
                                type: string
                                description: Session ID
                                example: Ut sunt praesentium natus sit harum.
                            example: Ab qui est earum aut facere.
                "400":
                    description: 'invalid_payload: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/users:
        get:
            tags:
                - users
            summary: list users
            operationId: users#list
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UserList'
                            example:
                                items:
                                    - id: 13835352590104114468
                                      name: Praesentium atque.
                                    - id: 13835352590104114468
                                      name: Praesentium atque.
                                    - id: 13835352590104114468
                                      name: Praesentium atque.
                                    - id: 13835352590104114468
                                      name: Praesentium atque.
                                offset: 0
                                total: 160
        post:
            tags:
                - users
            summary: create users
            operationId: users#create
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody4'
                        example:
                            email: Ut ad cupiditate non quam.
                            name: Voluptatem delectus natus libero.
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
                            example:
                                created_at: 2006-01-02T15:04:05Z07:00
                                id: 12381898749227116487
                                name: Id ratione quia aut voluptatum expedita.
                                updated_at: 2006-01-02T15:04:05Z07:00
                "400":
                    description: 'invalid_payload: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    schemas:
        Channel:
            type: object
            properties:
                created_at:
                    type: string
                    description: CreatedAt
                    example: 2006-01-02T15:04:05Z07:00
                    format: date-time
                id:
                    type: integer
                    description: ID
                    example: 8718287580780151072
                name:
                    type: string
                    description: Name
                    example: Culpa quaerat est cum libero.
                updated_at:
                    type: string
                    description: UpdatedAt
                    example: 2006-01-02T15:04:05Z07:00
                    format: date-time
            example:
                created_at: 2006-01-02T15:04:05Z07:00
                id: 14741321554373646403
                name: Fugiat magnam sapiente nihil quas.
                updated_at: 2006-01-02T15:04:05Z07:00
            required:
                - id
                - created_at
                - updated_at
                - name
        ChannelList:
            type: object
            properties:
                items:
                    $ref: '#/components/schemas/ChannelListItemCollection'
                offset:
                    type: integer
                    description: Offset
                    example: 0
                total:
                    type: integer
                    description: Total number of items
                    example: 160
            example:
                items:
                    - created_at: 2006-01-02T15:04:05Z07:00
                      id: 7271062959787804439
                      name: Eos et excepturi aut asperiores.
                      updated_at: 2006-01-02T15:04:05Z07:00
                    - created_at: 2006-01-02T15:04:05Z07:00
                      id: 7271062959787804439
                      name: Eos et excepturi aut asperiores.
                      updated_at: 2006-01-02T15:04:05Z07:00
                    - created_at: 2006-01-02T15:04:05Z07:00
                      id: 7271062959787804439
                      name: Eos et excepturi aut asperiores.
                      updated_at: 2006-01-02T15:04:05Z07:00
                    - created_at: 2006-01-02T15:04:05Z07:00
                      id: 7271062959787804439
                      name: Eos et excepturi aut asperiores.
                      updated_at: 2006-01-02T15:04:05Z07:00
                offset: 0
                total: 160
            required:
                - items
                - total
                - offset
        ChannelListItem:
            type: object
            properties:
                created_at:
                    type: string
                    description: CreatedAt
                    example: 2006-01-02T15:04:05Z07:00
                    format: date-time
                id:
                    type: integer
                    description: ID
                    example: 7640296165610347364
                name:
                    type: string
                    description: Name
                    example: Et autem nesciunt veritatis.
                updated_at:
                    type: string
                    description: UpdatedAt
                    example: 2006-01-02T15:04:05Z07:00
                    format: date-time
            example:
                created_at: 2006-01-02T15:04:05Z07:00
                id: 2127195729179436326
                name: Et quia aliquam quaerat reiciendis.
                updated_at: 2006-01-02T15:04:05Z07:00
            required:
                - id
                - created_at
                - updated_at
                - name
        ChannelListItemCollection:
            type: array
            items:
                $ref: '#/components/schemas/ChannelListItem'
            example:
                - created_at: 2006-01-02T15:04:05Z07:00
                  id: 7271062959787804439
                  name: Eos et excepturi aut asperiores.
                  updated_at: 2006-01-02T15:04:05Z07:00
                - created_at: 2006-01-02T15:04:05Z07:00
                  id: 7271062959787804439
                  name: Eos et excepturi aut asperiores.
                  updated_at: 2006-01-02T15:04:05Z07:00
        ChatMessage:
            type: object
            properties:
                channel_id:
                    type: integer
                    description: Channel ID
                    example: 11229479667587510163
                content:
                    type: string
                    description: Content
                    example: Accusamus ut aliquid similique quisquam.
                created_at:
                    type: string
                    description: CreatedAt
                    example: 2006-01-02T15:04:05Z07:00
                    format: date-time
                id:
                    type: integer
                    description: ID
                    example: 14505295020005311774
                updated_at:
                    type: string
                    description: UpdatedAt
                    example: 2006-01-02T15:04:05Z07:00
                    format: date-time
                user_id:
                    type: integer
                    description: User ID
                    example: 11170095463107705324
                user_name:
                    type: string
                    description: User Name
                    example: In expedita sint laboriosam et delectus.
            example:
                channel_id: 18164880466960210329
                content: A commodi nisi eligendi maiores.
                created_at: 2006-01-02T15:04:05Z07:00
                id: 8426138171250990874
                updated_at: 2006-01-02T15:04:05Z07:00
                user_id: 7572078204324101450
                user_name: Quas aut facilis itaque.
            required:
                - id
                - created_at
                - updated_at
                - channel_id
                - user_name
                - content
        ChatMessageList:
            type: object
            properties:
                items:
                    $ref: '#/components/schemas/ChatMessageListItemCollection'
            example:
                items:
                    - channel_id: 17409760595284137384
                      content: Et est nesciunt perspiciatis optio rerum.
                      created_at: 2006-01-02T15:04:05Z07:00
                      id: 6470953216617523288
                      updated_at: 2006-01-02T15:04:05Z07:00
                      user_id: 3571536357390730231
                      user_name: Repudiandae consequatur officia dolores corporis asperiores.
                    - channel_id: 17409760595284137384
                      content: Et est nesciunt perspiciatis optio rerum.
                      created_at: 2006-01-02T15:04:05Z07:00
                      id: 6470953216617523288
                      updated_at: 2006-01-02T15:04:05Z07:00
                      user_id: 3571536357390730231
                      user_name: Repudiandae consequatur officia dolores corporis asperiores.
                    - channel_id: 17409760595284137384
                      content: Et est nesciunt perspiciatis optio rerum.
                      created_at: 2006-01-02T15:04:05Z07:00
                      id: 6470953216617523288
                      updated_at: 2006-01-02T15:04:05Z07:00
                      user_id: 3571536357390730231
                      user_name: Repudiandae consequatur officia dolores corporis asperiores.
            required:
                - items
        ChatMessageListItem:
            type: object
            properties:
                channel_id:
                    type: integer
                    description: Channel ID
                    example: 453158392406397939
                content:
                    type: string
                    description: Content
                    example: Iusto deserunt quo.
                created_at:
                    type: string
                    description: CreatedAt
                    example: 2006-01-02T15:04:05Z07:00
                    format: date-time
                id:
                    type: integer
                    description: ID
                    example: 17635560002842779066
                updated_at:
                    type: string
                    description: UpdatedAt
                    example: 2006-01-02T15:04:05Z07:00
                    format: date-time
                user_id:
                    type: integer
                    description: User ID
                    example: 11609187672318409864
                user_name:
                    type: string
                    description: User Name
                    example: Unde officia.
            example:
                channel_id: 12034538003190253002
                content: Enim praesentium nesciunt.
                created_at: 2006-01-02T15:04:05Z07:00
                id: 1299359118782125740
                updated_at: 2006-01-02T15:04:05Z07:00
                user_id: 5487687067080848182
                user_name: Aliquid eos sit.
            required:
                - id
                - created_at
                - updated_at
                - channel_id
                - user_name
                - content
        ChatMessageListItemCollection:
            type: array
            items:
                $ref: '#/components/schemas/ChatMessageListItem'
            example:
                - channel_id: 17409760595284137384
                  content: Et est nesciunt perspiciatis optio rerum.
                  created_at: 2006-01-02T15:04:05Z07:00
                  id: 6470953216617523288
                  updated_at: 2006-01-02T15:04:05Z07:00
                  user_id: 3571536357390730231
                  user_name: Repudiandae consequatur officia dolores corporis asperiores.
                - channel_id: 17409760595284137384
                  content: Et est nesciunt perspiciatis optio rerum.
                  created_at: 2006-01-02T15:04:05Z07:00
                  id: 6470953216617523288
                  updated_at: 2006-01-02T15:04:05Z07:00
                  user_id: 3571536357390730231
                  user_name: Repudiandae consequatur officia dolores corporis asperiores.
                - channel_id: 17409760595284137384
                  content: Et est nesciunt perspiciatis optio rerum.
                  created_at: 2006-01-02T15:04:05Z07:00
                  id: 6470953216617523288
                  updated_at: 2006-01-02T15:04:05Z07:00
                  user_id: 3571536357390730231
                  user_name: Repudiandae consequatur officia dolores corporis asperiores.
                - channel_id: 17409760595284137384
                  content: Et est nesciunt perspiciatis optio rerum.
                  created_at: 2006-01-02T15:04:05Z07:00
                  id: 6470953216617523288
                  updated_at: 2006-01-02T15:04:05Z07:00
                  user_id: 3571536357390730231
                  user_name: Repudiandae consequatur officia dolores corporis asperiores.
        CreateRequestBody:
            type: object
            properties:
                name:
                    type: string
                    description: Name
                    example: Et ab deleniti.
            example:
                name: Sint maxime explicabo aliquam inventore.
            required:
                - name
        CreateRequestBody2:
            type: object
            properties:
                channel_id:
                    type: integer
                    description: Channel ID
                    example: 5706178893794023756
                content:
                    type: string
                    description: Content
                    example: Ad velit sequi quia officiis natus dolorem.
            example:
                channel_id: 3487991190734770437
                content: Et animi.
            required:
                - channel_id
                - content
        CreateRequestBody3:
            type: object
            properties:
                id_token:
                    type: string
                    description: ID Token
                    example: Autem quo voluptatem ab mollitia esse quia.
            example:
                id_token: Fugiat alias qui.
            required:
                - id_token
        CreateRequestBody4:
            type: object
            properties:
                email:
                    type: string
                    description: Email
                    example: Est consequatur dolor reprehenderit.
                name:
                    type: string
                    description: Name
                    example: Repellat incidunt.
            example:
                email: Quidem voluptatem voluptatem provident sunt.
                name: Porro maiores consequatur.
            required:
                - name
                - email
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        UpdateRequestBody:
            type: object
            properties:
                content:
                    type: string
                    description: Content
                    example: Reprehenderit voluptatum ducimus sapiente.
            example:
                content: Quibusdam quo omnis modi aut necessitatibus.
            required:
                - content
        User:
            type: object
            properties:
                created_at:
                    type: string
                    description: CreatedAt
                    example: 2006-01-02T15:04:05Z07:00
                    format: date-time
                id:
                    type: integer
                    description: ID
                    example: 13607136191731716706
                name:
                    type: string
                    description: Name
                    example: Aut doloremque inventore.
                updated_at:
                    type: string
                    description: UpdatedAt
                    example: 2006-01-02T15:04:05Z07:00
                    format: date-time
            example:
                created_at: 2006-01-02T15:04:05Z07:00
                id: 7643201742503832471
                name: Ut cum corrupti inventore enim sed.
                updated_at: 2006-01-02T15:04:05Z07:00
            required:
                - id
                - created_at
                - updated_at
                - name
        UserList:
            type: object
            properties:
                items:
                    $ref: '#/components/schemas/UserListItemCollection'
                offset:
                    type: integer
                    description: Offset
                    example: 0
                total:
                    type: integer
                    description: Total number of items
                    example: 160
            example:
                items:
                    - id: 13835352590104114468
                      name: Praesentium atque.
                    - id: 13835352590104114468
                      name: Praesentium atque.
                    - id: 13835352590104114468
                      name: Praesentium atque.
                    - id: 13835352590104114468
                      name: Praesentium atque.
                offset: 0
                total: 160
            required:
                - items
                - total
                - offset
        UserListItem:
            type: object
            properties:
                id:
                    type: integer
                    description: ID
                    example: 16729169049061569038
                name:
                    type: string
                    description: Name
                    example: Eum facilis id.
            example:
                id: 11749666525437877988
                name: Qui nesciunt non modi natus maiores.
            required:
                - id
                - name
        UserListItemCollection:
            type: array
            items:
                $ref: '#/components/schemas/UserListItem'
            example:
                - id: 13835352590104114468
                  name: Praesentium atque.
                - id: 13835352590104114468
                  name: Praesentium atque.
tags:
    - name: channels
    - name: chat_messages
    - name: sessions
    - name: users
